number = 6
slug = "006-exported-globals"
status = "completed"
description = "Add support for cross-unit global variable access. Units may export global va..."
role = "production"
context_files = []
created_at = "2026-04-13T10:36:15"
completed_at = "2026-04-13T13:57:55"
commits = ["473fc947fab8d50c98e3fb4052f9bac754eadbb1"]
